x-pdi-common:
  &pdi-common
  build:
    context: ./setup-pentaho
    dockerfile: Dockerfile
    args:
      PENTAHO_UID: ${PENTAHO_UID}
      PENTAHO_GID: ${PENTAHO_GID}
  image: pdi
  environment:
    &pdi-common-env
    HOST_ENV: ${HOST_ENV:-localhost}
    PENTAHO_DI_JAVA_OPTIONS: ${PENTAHO_DI_JAVA_OPTIONS}
    CARTE_USER: ${CARTE_USER}
    CARTE_PASSWORD: ${CARTE_PASSWORD}
    PDI_TEST_WELCOME_MESSAGE: "Welcome to pentaho DI (kettle)"
  volumes:
    # - /var/run/docker.sock:/var/run/docker.sock
    - ./source-code/ktrs:/home/pentaho/repositories
    - ./setup-pentaho/logs:/opt/data-integration/logs:rw
    - ./setup-pentaho/repositories.xml:/opt/data-integration/.kettle/repositories.xml
    - ./setup-pentaho/kettle-properties/${HOST_ENV:-localhost}-kettle.properties:/opt/data-integration/.kettle/kettle.properties
    - ./setup-pentaho/simple-jndi:/opt/data-integration/simple-jndi
  deploy:
    restart_policy:
      condition: on-failure
      max_attempts: 3

x-airflow-common:
  &airflow-common
  build: ./setup-airflow
  image: airflow
  networks:
    - pentaho-network
  environment:
    &airflow-common-env
    HOST_ENV: ${HOST_ENV}
    AIRFLOW_UID: ${AIRFLOW_UID}
    AIRFLOW_GID: ${AIRFLOW_GID}
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-database/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@airflow-database/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://:@airflow-broker:6379/0
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__TEST_CONNECTION: 'enabled'
    _AIRFLOW_CONN_DATAHUB: 'datahub-rest://http://datahub-gms%3A8080'
    AIRFLOW_CONN_DATAHUB: 'datahub-rest://http://datahub-gms%3A8080'
    PDI_CONN_STR: http://${CARTE_USER:-cluster}:${CARTE_PASSWORD:-cluster}@pdi-master:${CARTE_HOST_PORT:-8181}
    DAG_FOLDER: /opt/airflow/dags
  volumes:
    - ./source-code/dags:/opt/airflow/dags
    - ./setup-airflow/plugins:/opt/airflow/plugins
    - airflow-logs:/opt/airflow/logs
    - ./setup-airflow/execute-carte.sh:/opt/airflow/execute-carte.sh
    - ./setup-airflow/airflow.cfg:/opt/airflow/airflow.cfg


services:

  # ---------------------------------------------------
  # --- MariaDB
  # ---------------------------------------------------
  db-mariadb:
    image: mariadb:11.4.2
    hostname: db-mariadb
    container_name: db-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
      - ./setup-mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pentaho-network
    expose:
      - 3306
    ports:
      - "4406:3306"

  # ---------------------------------------------------
  # --- Mongo
  # ---------------------------------------------------
  db-mongo:
      image: docker.io/mongo:7.0.14-jammy
      restart: always
      hostname: db-mongodb
      container_name: db-mongodb
      pull_policy: missing
      networks:
          - pentaho-network
      deploy:
        restart_policy:
          condition: on-failure
      volumes:
        - mongo-data:/data/db
        - ./setup-mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      env_file:
        - .env
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      command:
        - --auth
        - --bind_ip_all
        - --setParameter=enableLocalhostAuthBypass=true
        - --timeStampFormat=iso8601-utc
      healthcheck:
        test: echo 'db.runCommand({find:"app_db_name.devUser"}).ok' | mongosh --authenticationDatabase admin --host localhost -u ${MONGO_ROOT_USERNAME} -p ${MONGO_ROOT_PASSWORD} admin --quiet | grep -q 1
        interval: 10s
        timeout: 60s
        retries: 3
        start_period: 20s
      expose:
        - 27017
      ports:
        - "27017:27017"

# Airflow-DB
  airflow-database:
    image: postgres:13
    container_name: airflow-database
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - pentaho-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always

# Airflow-messenger
  airflow-broker:
    image: redis:latest
    container_name: airflow-broker
    ports:
      - 6379:6379
    networks:
      - pentaho-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always
    depends_on:
      airflow-datahub-connection-init:
        condition: service_completed_successfully

# Airflow-webserver
  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - ${AIRFLOW_HOST_PORT:-9080}:8080
    networks:
      - pentaho-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:${AIRFLOW_HOST_PORT:-8080}/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      airflow-broker:
        condition: service_healthy
      airflow-database:
        condition: service_healthy
      datahub-gms:
        condition: service_healthy

# Airflow-scheduler
  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    restart: always
    networks:
      - pentaho-network
    depends_on:
      airflow-broker:
        condition: service_healthy
      airflow-database:
        condition: service_healthy
      datahub-gms:
        condition: service_healthy

# Airflow-worker
  airflow-worker:
    <<: *airflow-common
    command: celery worker
    container_name: airflow-worker
    restart: always
    networks:
      - pentaho-network
    depends_on:
      airflow-broker:
        condition: service_healthy
      airflow-database:
        condition: service_healthy
      datahub-gms:
        condition: service_healthy

# Airflow-DB-initialize
  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    command: version
    networks:
      - pentaho-network
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_ADMIN_USER:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_ADMIN_PASSWORD:-airflow}
      _AIRFLOW_WWW_USER_EMAIL: ${AIRFLOW_ADMIN_EMAIL:-admin@admin.com}
      _AIRFLOW_CONN_DATAHUB: 'datahub-rest://http://datahub-gms%3A8080'
      AIRFLOW_CONN_DATAHUB: 'datahub-rest://http://datahub-gms%3A8080'
    depends_on:
      airflow-database:
        condition: service_healthy


  airflow-datahub-connection-init:
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    image: postgres:13
    container_name: airflow-datahub-connection
    networks:
      - pentaho-network
    environment:
      DB_SERVER: "airflow-database"
      DB_PORT: 5432
      DB_NAME: "airflow"
      PGUSER: "airflow"
      PGPASSWORD: "airflow"
    volumes:
      - ./setup-airflow/datahub-connection-row.sql:/home/datahub-connection-row.sql
    command: >
      bash -c "psql -h airflow-database -p 5432 -d airflow -f /home/datahub-connection-row.sql" 

# Pentaho
  pdi-master:
    << : *pdi-common
    container_name: pdi-master
    user: root
    environment:
      <<: *pdi-common-env
    ports:
      - ${CARTE_HOST_PORT:-8181}:8181
    networks:
      - pentaho-network

  # pdi-child:
  #   << : *pdi-common
  #   container_name: pdi-child
  #   ports:
  #     - 8182
  #   depends_on:
  #     - pdi-master
  #   environment:
  #     <<: *pdi-common-env
  #     CARTE_PORT: 8182
  #     CARTE_IS_MASTER: 'N'
  #     CARTE_INCLUDE_MASTERS: 'Y'
  #     CARTE_MASTER_HOSTNAME: 'pdi-master'
  #     CARTE_MASTER_PORT: ${CARTE_HOST_PORT:-8181}

#####################################################
# DATAHUB services
#####################################################
  broker:
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
    - KAFKA_BROKER_ID=1
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
    - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
    - KAFKA_HEAP_OPTS=-Xms256m -Xmx256m
    - KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=false
    - KAFKA_MESSAGE_MAX_BYTES=5242880
    - KAFKA_MAX_MESSAGE_BYTES=5242880
    healthcheck:
      interval: 1s
      retries: 5
      start_period: 60s
      test: nc -z broker $${DATAHUB_KAFKA_BROKER_PORT:-9092}
      timeout: 5s
    hostname: broker
    container_name: datahub-broker
    image: ${DATAHUB_CONFLUENT_KAFKA_IMAGE:-confluentinc/cp-kafka}:${DATAHUB_CONFLUENT_VERSION:-7.4.0}
    ports:
    - ${DATAHUB_MAPPED_KAFKA_BROKER_PORT:-9092}:9092
    volumes:
    - broker:/var/lib/kafka/data/
    networks:
      - pentaho-network

  datahub-actions:
    depends_on:
      datahub-gms:
        condition: service_healthy
    environment:
    - ACTIONS_CONFIG=${ACTIONS_CONFIG:-}
    - ACTIONS_EXTRA_PACKAGES=${ACTIONS_EXTRA_PACKAGES:-}
    - DATAHUB_GMS_HOST=datahub-gms
    - DATAHUB_GMS_PORT=8080
    - DATAHUB_GMS_PROTOCOL=http
    - DATAHUB_SYSTEM_CLIENT_ID=__datahub_system
    - DATAHUB_SYSTEM_CLIENT_SECRET=JohnSnowKnowsNothing
    - KAFKA_BOOTSTRAP_SERVER=broker:29092
    - KAFKA_PROPERTIES_SECURITY_PROTOCOL=PLAINTEXT
    - METADATA_AUDIT_EVENT_NAME=MetadataAuditEvent_v4
    - METADATA_CHANGE_LOG_VERSIONED_TOPIC_NAME=MetadataChangeLog_Versioned_v1
    - SCHEMA_REGISTRY_URL=http://schema-registry:8081
    hostname: actions
    image: ${DATAHUB_ACTIONS_IMAGE:-acryldata/datahub-actions}:${ACTIONS_VERSION:-head}
    networks:
      - pentaho-network
    container_name: datahub-actions


  datahub-frontend-react:
    depends_on:
      datahub-gms:
        condition: service_healthy
    environment:
    - DATAHUB_GMS_HOST=datahub-gms
    - DATAHUB_GMS_PORT=8080
    - DATAHUB_SECRET=YouKnowNothing
    - DATAHUB_APP_VERSION=1.0
    - DATAHUB_PLAY_MEM_BUFFER_SIZE=10MB
    - JAVA_OPTS=-Xms512m -Xmx512m -Dhttp.port=9002 -Dconfig.file=datahub-frontend/conf/application.conf -Djava.security.auth.login.config=datahub-frontend/conf/jaas.conf -Dlogback.configurationFile=datahub-frontend/conf/logback.xml -Dlogback.debug=false -Dpidfile.path=/dev/null
    - KAFKA_BOOTSTRAP_SERVER=broker:29092
    - DATAHUB_TRACKING_TOPIC=DataHubUsageEvent_v1
    - ELASTIC_CLIENT_HOST=elasticsearch
    - ELASTIC_CLIENT_PORT=9200
    hostname: datahub-frontend-react
    container_name: datahub-frontend-react
    image: ${DATAHUB_FRONTEND_IMAGE:-acryldata/datahub-frontend-react}:${DATAHUB_VERSION:-head}
    ports:
    - ${DATAHUB_MAPPED_FRONTEND_PORT:-9002}:9002
    volumes:
    - ${HOME}/.datahub/plugins:/etc/datahub/plugins
    networks:
      - pentaho-network

  datahub-gms:
    depends_on:
      datahub-upgrade:
        condition: service_completed_successfully
    environment:
    - DATAHUB_SERVER_TYPE=${DATAHUB_SERVER_TYPE:-quickstart}
    - DATAHUB_TELEMETRY_ENABLED=${DATAHUB_TELEMETRY_ENABLED:-true}
    - DATAHUB_UPGRADE_HISTORY_KAFKA_CONSUMER_GROUP_ID=generic-duhe-consumer-job-client-gms
    - EBEAN_DATASOURCE_DRIVER=com.mysql.jdbc.Driver
    - EBEAN_DATASOURCE_HOST=mysql:3306
    - EBEAN_DATASOURCE_PASSWORD=datahub
    - EBEAN_DATASOURCE_URL=jdbc:mysql://mysql:3306/datahub?verifyServerCertificate=false&useSSL=true&useUnicode=yes&characterEncoding=UTF-8
    - EBEAN_DATASOURCE_USERNAME=datahub
    - ELASTICSEARCH_HOST=elasticsearch
    - ELASTICSEARCH_INDEX_BUILDER_MAPPINGS_REINDEX=true
    - ELASTICSEARCH_INDEX_BUILDER_SETTINGS_REINDEX=true
    - ELASTICSEARCH_PORT=9200
    - ENTITY_REGISTRY_CONFIG_PATH=/datahub/datahub-gms/resources/entity-registry.yml
    - ENTITY_SERVICE_ENABLE_RETENTION=true
    - ES_BULK_REFRESH_POLICY=WAIT_UNTIL
    - GRAPH_SERVICE_DIFF_MODE_ENABLED=true
    - GRAPH_SERVICE_IMPL=elasticsearch
    - JAVA_OPTS=-Xms1g -Xmx1g
    - KAFKA_BOOTSTRAP_SERVER=broker:29092
    - KAFKA_CONSUMER_STOP_ON_DESERIALIZATION_ERROR=${KAFKA_CONSUMER_STOP_ON_DESERIALIZATION_ERROR:-true}
    - KAFKA_SCHEMAREGISTRY_URL=http://schema-registry:8081
    - MAE_CONSUMER_ENABLED=true
    - MCE_CONSUMER_ENABLED=true
    - PE_CONSUMER_ENABLED=true
    - UI_INGESTION_ENABLED=true
    healthcheck:
      interval: 1s
      retries: 3
      start_period: 90s
      test: curl -sS --fail http://datahub-gms:${DATAHUB_GMS_PORT:-8080}/health
      timeout: 5s
    hostname: datahub-gms
    container_name: datahub-gms
    image: ${DATAHUB_GMS_IMAGE:-acryldata/datahub-gms}:${DATAHUB_VERSION:-head}
    ports:
    - ${DATAHUB_MAPPED_GMS_PORT:-8080}:8080
    volumes:
    - ${HOME}/.datahub/plugins:/etc/datahub/plugins
    networks:
      - pentaho-network


  datahub-upgrade:
    command:
    - -u
    - SystemUpdate
    depends_on:
      elasticsearch-setup:
        condition: service_completed_successfully
      kafka-setup:
        condition: service_completed_successfully
      mysql-setup:
        condition: service_completed_successfully
    environment:
    - EBEAN_DATASOURCE_USERNAME=datahub
    - EBEAN_DATASOURCE_PASSWORD=datahub
    - EBEAN_DATASOURCE_HOST=mysql:3306
    - EBEAN_DATASOURCE_URL=jdbc:mysql://mysql:3306/datahub?verifyServerCertificate=false&useSSL=true&useUnicode=yes&characterEncoding=UTF-8
    - EBEAN_DATASOURCE_DRIVER=com.mysql.jdbc.Driver
    - KAFKA_BOOTSTRAP_SERVER=broker:29092
    - KAFKA_SCHEMAREGISTRY_URL=http://schema-registry:8081
    - ELASTICSEARCH_HOST=elasticsearch
    - ELASTICSEARCH_PORT=9200
    - ELASTICSEARCH_INDEX_BUILDER_MAPPINGS_REINDEX=true
    - ELASTICSEARCH_INDEX_BUILDER_SETTINGS_REINDEX=true
    - ELASTICSEARCH_BUILD_INDICES_CLONE_INDICES=false
    - GRAPH_SERVICE_IMPL=elasticsearch
    - DATAHUB_GMS_HOST=datahub-gms
    - DATAHUB_GMS_PORT=8080
    - ENTITY_REGISTRY_CONFIG_PATH=/datahub/datahub-gms/resources/entity-registry.yml
    - BACKFILL_BROWSE_PATHS_V2=true
    - REPROCESS_DEFAULT_BROWSE_PATHS_V2=false
    hostname: datahub-upgrade
    container_name: datahub-upgrade
    image: ${DATAHUB_UPGRADE_IMAGE:-acryldata/datahub-upgrade}:${DATAHUB_VERSION:-head}
    labels:
      datahub_setup_job: true
    networks:
      - pentaho-network

  elasticsearch:
    deploy:
      resources:
        limits:
          memory: 1G
    environment:
    - discovery.type=single-node
    - ${XPACK_SECURITY_ENABLED:-xpack.security.enabled=false}
    - ES_JAVA_OPTS=-Xms256m -Xmx512m -Dlog4j2.formatMsgNoLookups=true
    - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m -Dlog4j2.formatMsgNoLookups=true
    healthcheck:
      interval: 1s
      retries: 3
      start_period: 20s
      test: curl -sS --fail http://elasticsearch:$${DATAHUB_ELASTIC_PORT:-9200}/_cluster/health?wait_for_status=yellow&timeout=0s
      timeout: 5s
    hostname: elasticsearch
    container_name: elasticsearch
    image: ${DATAHUB_SEARCH_IMAGE:-elasticsearch}:${DATAHUB_SEARCH_TAG:-7.10.1}
    ports:
    - ${DATAHUB_MAPPED_ELASTIC_PORT:-9200}:9200
    volumes:
    - esdata:/usr/share/elasticsearch/data
    networks:
      - pentaho-network

  elasticsearch-setup:
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
    - ELASTICSEARCH_USE_SSL=${ELASTICSEARCH_USE_SSL:-false}
    - USE_AWS_ELASTICSEARCH=${USE_AWS_ELASTICSEARCH:-false}
    - ELASTICSEARCH_HOST=elasticsearch
    - ELASTICSEARCH_PORT=9200
    - ELASTICSEARCH_PROTOCOL=http
    hostname: elasticsearch-setup
    container_name: elasticsearch-setup
    image: ${DATAHUB_ELASTIC_SETUP_IMAGE:-acryldata/datahub-elasticsearch-setup}:${DATAHUB_VERSION:-head}
    labels:
      datahub_setup_job: true
    networks:
      - pentaho-network

  kafka-setup:
    depends_on:
      broker:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    environment:
    - DATAHUB_PRECREATE_TOPICS=${DATAHUB_PRECREATE_TOPICS:-false}
    - KAFKA_BOOTSTRAP_SERVER=broker:29092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - USE_CONFLUENT_SCHEMA_REGISTRY=TRUE
    hostname: kafka-setup
    container_name: kafka-setup
    image: ${DATAHUB_KAFKA_SETUP_IMAGE:-acryldata/datahub-kafka-setup}:${DATAHUB_VERSION:-head}
    labels:
      datahub_setup_job: true
    networks:
      - pentaho-network

  mysql:
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default-authentication-plugin=mysql_native_password
    environment:
    - MYSQL_DATABASE=datahub
    - MYSQL_USER=datahub
    - MYSQL_PASSWORD=datahub
    - MYSQL_ROOT_PASSWORD=datahub
    healthcheck:
      interval: 1s
      retries: 30
      start_period: 20s
      test: mysqladmin ping -h mysql -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 5s
    hostname: mysql
    container_name: mysql
    image: mysql:${DATAHUB_MYSQL_VERSION:-8.2}
    ports:
    - ${DATAHUB_MAPPED_MYSQL_PORT:-3306}:3306
    restart: on-failure
    volumes:
    - mysqldata:/var/lib/mysql
    networks:
      - pentaho-network

  mysql-setup:
    depends_on:
      mysql:
        condition: service_healthy
    environment:
    - MYSQL_HOST=mysql
    - MYSQL_PORT=3306
    - MYSQL_USERNAME=datahub
    - MYSQL_PASSWORD=datahub
    - DATAHUB_DB_NAME=datahub
    hostname: mysql-setup
    container_name: mysql-setup
    image: ${DATAHUB_MYSQL_SETUP_IMAGE:-acryldata/datahub-mysql-setup}:${DATAHUB_VERSION:-head}
    labels:
      datahub_setup_job: true
    networks:
      - pentaho-network

  schema-registry:
    depends_on:
      broker:
        condition: service_healthy
    environment:
    - SCHEMA_REGISTRY_HOST_NAME=schemaregistry
    - SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL=PLAINTEXT
    - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=broker:29092
    healthcheck:
      interval: 1s
      retries: 3
      start_period: 60s
      test: nc -z schema-registry ${DATAHUB_SCHEMA_REGISTRY_PORT:-8081}
      timeout: 5s
    hostname: schema-registry
    container_name: kafka-schema-registry
    image: ${DATAHUB_CONFLUENT_SCHEMA_REGISTRY_IMAGE:-confluentinc/cp-schema-registry}:${DATAHUB_CONFLUENT_VERSION:-7.4.0}
    ports:
    - ${DATAHUB_MAPPED_SCHEMA_REGISTRY_PORT:-8081}:8081
    networks:
      - pentaho-network

  zookeeper:
    environment:
    - ZOOKEEPER_CLIENT_PORT=2181
    - ZOOKEEPER_TICK_TIME=2000
    healthcheck:
      interval: 5s
      retries: 3
      start_period: 30s
      test: echo srvr | nc zookeeper $${DATAHUB_ZK_PORT:-2181}
      timeout: 5s
    hostname: zookeeper
    container_name: zookeeper
    image: ${DATAHUB_CONFLUENT_ZOOKEEPER_IMAGE:-confluentinc/cp-zookeeper}:${DATAHUB_CONFLUENT_VERSION:-7.4.0}
    ports:
    - ${DATAHUB_MAPPED_ZK_PORT:-2181}:2181
    volumes:
    - zkdata:/var/lib/zookeeper/data
    - zklogs:/var/lib/zookeeper/log
    networks:
      - pentaho-network

volumes:
  postgres-db-volume:
  airflow-logs:
  data:
  mongo-data:
  broker: null
  esdata: null
  mysqldata: null
  zkdata: null
  zklogs: null

networks:
  pentaho-network:
    name: pentaho-network